name: CI

on: [pull_request, push]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: --deny warnings

jobs:
  style:
    name: Check basic style
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - run: ./.github/check-basic-style.sh

  check:
    name: 'Build & test'
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - run: cargo build
    - run: cargo test
    - run: cargo doc

  check-with-msrv:
    name: 'Build & test with Rust 1.60'
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Install Rust 1.60
      uses: actions-rs/toolchain@v1
      with:
          toolchain: 1.60.0
          override: true
          profile: minimal
    - run: cargo build
    - run: cargo test
    - run: cargo doc
